webtalk_init -webtalk_dir C:/Users/kaush/Documents/ECE383_Dan/Final_Project/Tests/IR_SENSOR_TEST_v1/ir_sensor_test.sim/sim_1/behav/xsim/xsim.dir/ir_test_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun May  5 04:54:28 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "772be553-31ac-49ef-a994-ba390a951cf8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "27ee40c21eaf468bb5859eefcc7b9eeb" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "84" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i7-1255U" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2611 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "100010 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "3.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "15268_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1212063926 -regid "" -xml C:/Users/kaush/Documents/ECE383_Dan/Final_Project/Tests/IR_SENSOR_TEST_v1/ir_sensor_test.sim/sim_1/behav/xsim/xsim.dir/ir_test_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/kaush/Documents/ECE383_Dan/Final_Project/Tests/IR_SENSOR_TEST_v1/ir_sensor_test.sim/sim_1/behav/xsim/xsim.dir/ir_test_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/kaush/Documents/ECE383_Dan/Final_Project/Tests/IR_SENSOR_TEST_v1/ir_sensor_test.sim/sim_1/behav/xsim/xsim.dir/ir_test_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
